version: "3.7"

services:
  web:
#    user: "${DOCKER_USER}"
    build:
      context: .
      dockerfile: "./docker/web/Dockerfile"
#      args:
#        USER: $USER
    ports:
      - "80:80"
    environment:
      TZ: Europe/Rome
    volumes:
      - ./src:/var/www
      - ./docker/web/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/web/conf.d/settings.ini:/usr/local/etc/php/conf.d/settings.ini